siteTitle="Laszlo Tamas – Full stack developer"
siteDescription="This is the personal website of Laszlo Tamas, a full stack developer, action sports enthusiast and nature lover."
siteKeywords="full stack developer, laszlo tamas"
linkPrefix = ""
